apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vw4s
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-vw4s@sha256:88586cab618b03b2f70302db0c9a0b89ed5ed43635be60bfb60a239ca00269a3
        name: my-nodejs
        resources: {}
status: {}
